/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedFieldRouteImport } from './routes/_authenticated.field'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated.portal.index'
import { Route as AuthenticatedFieldIndexRouteImport } from './routes/_authenticated.field.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedPortalVisitsRouteImport } from './routes/_authenticated.portal.visits'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated.portal.settings'
import { Route as AuthenticatedPortalReportsRouteImport } from './routes/_authenticated.portal.reports'
import { Route as AuthenticatedPortalReadinessRouteImport } from './routes/_authenticated.portal.readiness'
import { Route as AuthenticatedPortalQueriesRouteImport } from './routes/_authenticated.portal.queries'
import { Route as AuthenticatedPortalProgressRouteImport } from './routes/_authenticated.portal.progress'
import { Route as AuthenticatedPortalMilestonesRouteImport } from './routes/_authenticated.portal.milestones'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated.portal.documents'
import { Route as AuthenticatedFieldQueriesRouteImport } from './routes/_authenticated.field.queries'
import { Route as AuthenticatedFieldProgressRouteImport } from './routes/_authenticated.field.progress'
import { Route as AuthenticatedAdminVisitsRouteImport } from './routes/_authenticated.admin.visits'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated.admin.projects'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated.admin.notifications'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated.admin.documents'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAdminProjectsIndexRouteImport } from './routes/_authenticated.admin.projects.index'
import { Route as AuthenticatedAdminProjectsProjectIdRouteImport } from './routes/_authenticated.admin.projects.$projectId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFieldRoute = AuthenticatedFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedFieldIndexRoute = AuthenticatedFieldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFieldRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalVisitsRoute =
  AuthenticatedPortalVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalReportsRoute =
  AuthenticatedPortalReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalReadinessRoute =
  AuthenticatedPortalReadinessRouteImport.update({
    id: '/readiness',
    path: '/readiness',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalQueriesRoute =
  AuthenticatedPortalQueriesRouteImport.update({
    id: '/queries',
    path: '/queries',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProgressRoute =
  AuthenticatedPortalProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMilestonesRoute =
  AuthenticatedPortalMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedFieldQueriesRoute =
  AuthenticatedFieldQueriesRouteImport.update({
    id: '/queries',
    path: '/queries',
    getParentRoute: () => AuthenticatedFieldRoute,
  } as any)
const AuthenticatedFieldProgressRoute =
  AuthenticatedFieldProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedFieldRoute,
  } as any)
const AuthenticatedAdminVisitsRoute =
  AuthenticatedAdminVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProjectsIndexRoute =
  AuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)
const AuthenticatedAdminProjectsProjectIdRoute =
  AuthenticatedAdminProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/field': typeof AuthenticatedFieldRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/field/progress': typeof AuthenticatedFieldProgressRoute
  '/field/queries': typeof AuthenticatedFieldQueriesRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/milestones': typeof AuthenticatedPortalMilestonesRoute
  '/portal/progress': typeof AuthenticatedPortalProgressRoute
  '/portal/queries': typeof AuthenticatedPortalQueriesRoute
  '/portal/readiness': typeof AuthenticatedPortalReadinessRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/visits': typeof AuthenticatedPortalVisitsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/field/': typeof AuthenticatedFieldIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/field/progress': typeof AuthenticatedFieldProgressRoute
  '/field/queries': typeof AuthenticatedFieldQueriesRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/milestones': typeof AuthenticatedPortalMilestonesRoute
  '/portal/progress': typeof AuthenticatedPortalProgressRoute
  '/portal/queries': typeof AuthenticatedPortalQueriesRoute
  '/portal/readiness': typeof AuthenticatedPortalReadinessRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/visits': typeof AuthenticatedPortalVisitsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/field': typeof AuthenticatedFieldIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/field': typeof AuthenticatedFieldRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/_authenticated/field/progress': typeof AuthenticatedFieldProgressRoute
  '/_authenticated/field/queries': typeof AuthenticatedFieldQueriesRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/milestones': typeof AuthenticatedPortalMilestonesRoute
  '/_authenticated/portal/progress': typeof AuthenticatedPortalProgressRoute
  '/_authenticated/portal/queries': typeof AuthenticatedPortalQueriesRoute
  '/_authenticated/portal/readiness': typeof AuthenticatedPortalReadinessRoute
  '/_authenticated/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/visits': typeof AuthenticatedPortalVisitsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/field/': typeof AuthenticatedFieldIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/projects/$projectId': typeof AuthenticatedAdminProjectsProjectIdRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/field'
    | '/portal'
    | '/admin/audit'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/visits'
    | '/field/progress'
    | '/field/queries'
    | '/portal/documents'
    | '/portal/milestones'
    | '/portal/progress'
    | '/portal/queries'
    | '/portal/readiness'
    | '/portal/reports'
    | '/portal/settings'
    | '/portal/visits'
    | '/admin/'
    | '/field/'
    | '/portal/'
    | '/admin/projects/$projectId'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/audit'
    | '/admin/documents'
    | '/admin/notifications'
    | '/admin/users'
    | '/admin/visits'
    | '/field/progress'
    | '/field/queries'
    | '/portal/documents'
    | '/portal/milestones'
    | '/portal/progress'
    | '/portal/queries'
    | '/portal/readiness'
    | '/portal/reports'
    | '/portal/settings'
    | '/portal/visits'
    | '/admin'
    | '/field'
    | '/portal'
    | '/admin/projects/$projectId'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/field'
    | '/_authenticated/portal'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/visits'
    | '/_authenticated/field/progress'
    | '/_authenticated/field/queries'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/milestones'
    | '/_authenticated/portal/progress'
    | '/_authenticated/portal/queries'
    | '/_authenticated/portal/readiness'
    | '/_authenticated/portal/reports'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/visits'
    | '/_authenticated/admin/'
    | '/_authenticated/field/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/projects/$projectId'
    | '/_authenticated/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/field': {
      id: '/_authenticated/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AuthenticatedFieldRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/field/': {
      id: '/_authenticated/field/'
      path: '/'
      fullPath: '/field/'
      preLoaderRoute: typeof AuthenticatedFieldIndexRouteImport
      parentRoute: typeof AuthenticatedFieldRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/visits': {
      id: '/_authenticated/portal/visits'
      path: '/visits'
      fullPath: '/portal/visits'
      preLoaderRoute: typeof AuthenticatedPortalVisitsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/reports': {
      id: '/_authenticated/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof AuthenticatedPortalReportsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/readiness': {
      id: '/_authenticated/portal/readiness'
      path: '/readiness'
      fullPath: '/portal/readiness'
      preLoaderRoute: typeof AuthenticatedPortalReadinessRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/queries': {
      id: '/_authenticated/portal/queries'
      path: '/queries'
      fullPath: '/portal/queries'
      preLoaderRoute: typeof AuthenticatedPortalQueriesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/progress': {
      id: '/_authenticated/portal/progress'
      path: '/progress'
      fullPath: '/portal/progress'
      preLoaderRoute: typeof AuthenticatedPortalProgressRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/milestones': {
      id: '/_authenticated/portal/milestones'
      path: '/milestones'
      fullPath: '/portal/milestones'
      preLoaderRoute: typeof AuthenticatedPortalMilestonesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/field/queries': {
      id: '/_authenticated/field/queries'
      path: '/queries'
      fullPath: '/field/queries'
      preLoaderRoute: typeof AuthenticatedFieldQueriesRouteImport
      parentRoute: typeof AuthenticatedFieldRoute
    }
    '/_authenticated/field/progress': {
      id: '/_authenticated/field/progress'
      path: '/progress'
      fullPath: '/field/progress'
      preLoaderRoute: typeof AuthenticatedFieldProgressRouteImport
      parentRoute: typeof AuthenticatedFieldRoute
    }
    '/_authenticated/admin/visits': {
      id: '/_authenticated/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AuthenticatedAdminVisitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
    '/_authenticated/admin/projects/$projectId': {
      id: '/_authenticated/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
  }
}

interface AuthenticatedAdminProjectsRouteChildren {
  AuthenticatedAdminProjectsProjectIdRoute: typeof AuthenticatedAdminProjectsProjectIdRoute
  AuthenticatedAdminProjectsIndexRoute: typeof AuthenticatedAdminProjectsIndexRoute
}

const AuthenticatedAdminProjectsRouteChildren: AuthenticatedAdminProjectsRouteChildren =
  {
    AuthenticatedAdminProjectsProjectIdRoute:
      AuthenticatedAdminProjectsProjectIdRoute,
    AuthenticatedAdminProjectsIndexRoute: AuthenticatedAdminProjectsIndexRoute,
  }

const AuthenticatedAdminProjectsRouteWithChildren =
  AuthenticatedAdminProjectsRoute._addFileChildren(
    AuthenticatedAdminProjectsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVisitsRoute: typeof AuthenticatedAdminVisitsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVisitsRoute: AuthenticatedAdminVisitsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFieldRouteChildren {
  AuthenticatedFieldProgressRoute: typeof AuthenticatedFieldProgressRoute
  AuthenticatedFieldQueriesRoute: typeof AuthenticatedFieldQueriesRoute
  AuthenticatedFieldIndexRoute: typeof AuthenticatedFieldIndexRoute
}

const AuthenticatedFieldRouteChildren: AuthenticatedFieldRouteChildren = {
  AuthenticatedFieldProgressRoute: AuthenticatedFieldProgressRoute,
  AuthenticatedFieldQueriesRoute: AuthenticatedFieldQueriesRoute,
  AuthenticatedFieldIndexRoute: AuthenticatedFieldIndexRoute,
}

const AuthenticatedFieldRouteWithChildren =
  AuthenticatedFieldRoute._addFileChildren(AuthenticatedFieldRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalMilestonesRoute: typeof AuthenticatedPortalMilestonesRoute
  AuthenticatedPortalProgressRoute: typeof AuthenticatedPortalProgressRoute
  AuthenticatedPortalQueriesRoute: typeof AuthenticatedPortalQueriesRoute
  AuthenticatedPortalReadinessRoute: typeof AuthenticatedPortalReadinessRoute
  AuthenticatedPortalReportsRoute: typeof AuthenticatedPortalReportsRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalVisitsRoute: typeof AuthenticatedPortalVisitsRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalMilestonesRoute: AuthenticatedPortalMilestonesRoute,
  AuthenticatedPortalProgressRoute: AuthenticatedPortalProgressRoute,
  AuthenticatedPortalQueriesRoute: AuthenticatedPortalQueriesRoute,
  AuthenticatedPortalReadinessRoute: AuthenticatedPortalReadinessRoute,
  AuthenticatedPortalReportsRoute: AuthenticatedPortalReportsRoute,
  AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
  AuthenticatedPortalVisitsRoute: AuthenticatedPortalVisitsRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFieldRoute: typeof AuthenticatedFieldRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFieldRoute: AuthenticatedFieldRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
